# Desplegar deployment de prueba y servicio interno que enviara trafico a los pods desplegados
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-d
  template:
    metadata:
      labels:
        app: nginx-d
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 200m # milicpus 1 CPU = 1000 milicpus
        ports:
        - containerPort: 80
        volumeMounts:
        - name: persistent-storage
          mountPath: "/var/www/html" # Direcci√≥n en el Pod donde se monta
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-claim # Nuestro claim
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: nginx-d